SELECT ME.MEMBER_NAME AS MEMBER_NAME, 
        RE.REVIEW_TEXT AS REVIEW_TEXT, 
        DATE_FORMAT(RE.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW RE
    INNER JOIN MEMBER_PROFILE ME 
    ON RE.MEMBER_ID = ME.MEMBER_ID
WHERE RE.MEMBER_ID IN (
    SELECT * 
    FROM (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(MEMBER_ID) DESC
    LIMIT 1
    ) AS T
    
)
ORDER BY REVIEW_DATE
